default:
  image: python:3.11.3

stages:
    - static-analysis
    - build
    - test

isort:
    stage: static-analysis
    image: python:3.11.3
    script:
        - pip install isort
        - isort . --check-only
    only:
        - merge_requests
    allow_failure: true

flake8:
    stage: static-analysis
    image: python:3.11.3
    script:
        - pip install flake8
        - flake8 --max-line-length=120 .
    only:
        - merge_requests
    allow_failure: true

build and publish pip packages:
  stage: build
  script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install build
    - python -m build
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - main
  artifacts:
    paths:
      - dist/*.whl
    expire_in: 2 days

test packages:
  stage: test
  script:
    - pip install renops-scheduler --index-url https://gitlab+deploy-token-91:auD8AGBN9ZMaWzyV4sKS@gitlab.xlab.si/api/v4/projects/2476/packages/pypi/simple
    - echo 'print("hello world!")' > test.py
    - renops-scheduler test.py -la -r 1 -d 1 
  # only:
  #   - main
  # dependencies:
  #   - build
  #  - static-analysis

py38:
  stage: test
  image: python:3.8.0
    - test

py39:
  stage: test
  image: python:3.9.0
  only:
    - test

py310:
  stage: test
  image: python:3.10.0
  only:
    - test

py311:
  stage: test
  image: python:3.11.0
  only:
    - test

